In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [5]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cross_validation import cross_val_score

/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
nb = GaussianNB()
dt = DecisionTreeClassifier()
knn = KNeighborsClassifier(n_neighbors=3)

iris_nb_scores = cross_val_score(nb, iris.data, iris.target, cv=10)
iris_dt_scores = cross_val_score(dt, iris.data, iris.target, cv=10)
iris_knn_scores = cross_val_score(knn, iris.data, iris.target, cv=10)

vc = VotingClassifier(estimators=[('nb', nb), ('dt', dt), ('knn', knn)], voting='hard')
iris_vc_scores = cross_val_score(vc, iris.data, iris.target, cv=10)
print("Naive Bayes: \n", iris_nb_scores
     ,"\nDecision Tree: \n", iris_dt_scores
     ,"\nKNN: \n", iris_knn_scores
     ,"\nVoting Classifier: \n", iris_vc_scores)

Naive Bayes: 
 [0.93333333 0.93333333 1.         0.93333333 0.93333333 0.93333333
 0.86666667 1.         1.         1.        ] 
Decision Tree: 
 [1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 0.93333333 1.         1.        ] 
KNN: 
 [1.         0.93333333 1.         0.93333333 0.86666667 1.
 0.93333333 1.         1.         1.        ] 
Voting Classifier: 
 [1.         0.93333333 1.         0.93333333 0.93333333 0.93333333
 0.93333333 1.         1.         1.        ]


/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth valu

In [7]:
bc = BaggingClassifier(dt, n_estimators=100, max_samples=100, bootstrap=True, n_jobs=-1)
iris_bc_scores = cross_val_score(bc, iris.data, iris.target, cv=10)
iris_bc_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [8]:
rf = RandomForestClassifier(n_estimators=10)
iris_rf_scores = cross_val_score(rf, iris.data, iris.target, cv=10)
iris_rf_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.86666667,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

In [9]:
rf = RandomForestClassifier(n_estimators=10)
iris_rf = rf.fit(iris.data, iris.target)
pd.DataFrame({'features':iris["feature_names"], 'features_score':rf.feature_importances_})

features  features_score
0  sepal length (cm)        0.095572
1   sepal width (cm)        0.028490
2  petal length (cm)        0.547180
3   petal width (cm)        0.328758

In [10]:
ac = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=100, algorithm="SAMME.R", learning_rate=0.5)
iris_ac_scores = cross_val_score(ac, iris.data, iris.target, cv=10)
iris_ac_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.73333333, 0.86666667, 0.93333333, 1.        , 1.        ])

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = [{'learning_rate': [0.25, 0.5, 0.75, 1], 'n_estimators': [50,70,90,110]}]
ac_optim = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1))
grid_search = GridSearchCV(ac_optim, param_grid, cv=5, scoring='accuracy')
grid_search.fit(iris.data, iris.target)

GridSearchCV(cv=5, error_score='raise',
       estimator=AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=50, random_state=None),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'learning_rate': [0.25, 0.5, 0.75, 1], 'n_estimators': [50, 70, 90, 110]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [14]:
grid_search.best_params_

{'learning_rate': 0.5, 'n_estimators': 50}

In [15]:
ac = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=50, learning_rate=0.5)
iris_ac_scores = cross_val_score(ac, iris.data, iris.target, cv=10)
iris_ac_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.73333333, 0.93333333, 0.93333333, 1.        , 1.        ])

In [16]:
gc = GradientBoostingClassifier(max_depth=2, n_estimators=100)
iris_gc_scores = cross_val_score(gc, iris.data, iris.target, cv=10)
iris_gc_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 0.93333333, 1.        , 1.        ])