In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [3]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cross_validation import cross_val_score

/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
from sklearn.datasets import twenty_newsgroups

In [11]:
#ng20 = twenty_newsgroups.fetch_20newsgroups(subset='train', categories=['alt.atheism', 'rec.sport.baseball', 'comp.graphics', 'sci.med', 'soc.religion.christian', 'talk.politics.mideast'], remove=['headers','footers','quotes'])
ng20 = twenty_newsgroups.fetch_20newsgroups(subset='train', categories=['alt.atheism', 'rec.sport.baseball', 'comp.graphics'], remove=['headers','footers','quotes'])

In [12]:
ng20.target_names

['alt.atheism', 'comp.graphics', 'rec.sport.baseball']

In [13]:
len(ng20.data)

1661

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(stop_words='english', max_df=0.95)
ng20_occur = count_vect.fit_transform(ng20.data)
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=True).fit(ng20_occur)
ng20_tfidf = tf_transformer.transform(ng20_occur)

In [15]:
nb = GaussianNB()
dt = DecisionTreeClassifier()
knn = KNeighborsClassifier(n_neighbors=3)

ng20_nb_scores = cross_val_score(nb, ng20_tfidf.toarray(), ng20.target, cv=5)
ng20_dt_scores = cross_val_score(dt, ng20_tfidf.toarray(), ng20.target, cv=5)
ng20_knn_scores = cross_val_score(knn, ng20_tfidf.toarray(), ng20.target, cv=5)

vc = VotingClassifier(estimators=[('nb', nb), ('dt', dt), ('knn', knn)], voting='hard')
ng20_vc_scores = cross_val_score(vc, ng20_tfidf.toarray(), ng20.target, cv=5)
print("Naive Bayes: \n", ng20_nb_scores
     ,"\nDecision Tree: \n", ng20_dt_scores
     ,"\nKNN: \n", ng20_knn_scores
     ,"\nVoting Classifier: \n", ng20_vc_scores)

/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth valu

Naive Bayes: 
 [0.91591592 0.8978979  0.90963855 0.9246988  0.89425982] 
Decision Tree: 
 [0.77477477 0.73873874 0.75301205 0.76506024 0.7673716 ] 
KNN: 
 [0.42042042 0.38138138 0.35240964 0.36144578 0.3776435 ] 
Voting Classifier: 
 [0.85285285 0.8048048  0.82831325 0.84939759 0.8489426 ]


/Users/williamtjhi/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [16]:
bc = BaggingClassifier(dt, n_estimators=50, max_samples=500, bootstrap=True, n_jobs=-1)
ng20_bc_scores = cross_val_score(bc, ng20_tfidf.toarray(), ng20.target, cv=10)
ng20_bc_scores

array([0.79640719, 0.81437126, 0.77245509, 0.81437126, 0.79518072,
       0.77710843, 0.84939759, 0.80606061, 0.81212121, 0.83636364])

In [17]:
rf = RandomForestClassifier(n_estimators=50)
ng20_rf_scores = cross_val_score(rf, ng20_tfidf.toarray(), ng20.target, cv=10)
ng20_rf_scores

array([0.89221557, 0.89221557, 0.86826347, 0.91017964, 0.84939759,
       0.86144578, 0.90361446, 0.90909091, 0.86060606, 0.90909091])

In [ ]:
gc = GradientBoostingClassifier(max_depth=2, n_estimators=50)
ng20_gc_scores = cross_val_score(gc, ng20_tfidf.toarray(), ng20.target, cv=10)
ng20_gc_scores